name: 'Run golangci-lint with reviewdog'
description: 'Run golangci-lint with reviewdog on pull requests to improve code review experience.'
author: 'patil-ashutosh (reviewdog)'
inputs:
  github-token:
    description: 'GITHUB_TOKEN.'
    required: true
  golangci-lint-flags:
    description: 'golangci-lint flags.'
    default: ''
  tool-name:
    description: 'Tool name to use for reviewdog reporter'
    default: 'golangci'
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review,github-check].'
    default: 'github-pr-check'
  filter_mode:
    description: |
      Filtering for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
  workdir:
    description: 'Working directory relative to the root directory.'
    default: '.
runs:
  modules-download-mode: vendor  