codecov:
  require_ci_to_pass: yes
  token: 74498573-126a-4d45-a186-31e8cc8f6ee7

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project: # settings affecting project coverage
      default:
        target: auto # auto % coverage target
        threshold: 15%  # allow for 15% reduction of coverage without failing
        if_not_found: success
        if_ci_failed: error
        informational: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
