codecov:
  require_ci_to_pass: yes

coverage:
    precision: 2
    round: down
    range: "70...100"

    status:
      default: false  # disable the default status that measures entire project
      tests:  # declare a new status context "tests"
        target: 60%  # we always want 100% coverage here
        paths: "regex/"  # only include coverage in "tests/" folder
        patch: no
        changes: no
        informational: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
